/* ==========================================================================
   app.js — renders the page from data.js and handles the EN/FR toggle.

   You should not need to edit this file. All content lives in data.js.

   How it works, in short:
     * Every text field in data.js is { en: "...", fr: "..." }.
     * t(field) picks the string for the current language.
     * Static labels in index.html carry data-i18n="path.in.data.js".
     * Cards and skill groups are generated by looping over the data.
     * Switching language re-runs render(). No page reload, no storage,
       no network requests.
   ========================================================================== */

(function () {
  "use strict";

  var SVG_NS = "http://www.w3.org/2000/svg";
  var lang = "en";

  /* ---------- helpers ------------------------------------------------ */

  // Reads a dotted path out of the SITE object: pick("ui.nav.about").
  function pick(path) {
    return path.split(".").reduce(function (obj, key) {
      return obj == null ? obj : obj[key];
    }, SITE);
  }

  // Returns the string for the current language, falling back to English.
  // An empty string counts as "not translated yet", so a field with fr: ""
  // shows the English text rather than a blank space on the page.
  function t(field) {
    if (field == null) return "";
    if (typeof field === "string") return field;
    var value = field[lang];
    if (typeof value === "string" && value.trim() !== "") return value;
    return typeof field.en === "string" ? field.en : "";
  }

  // Tiny element builder: h("p", { class: "x" }, ["text", node])
  function h(tag, attrs, children) {
    var node = document.createElement(tag);
    if (attrs) {
      Object.keys(attrs).forEach(function (key) {
        if (attrs[key] == null) return;
        if (key === "text") node.textContent = attrs[key];
        else node.setAttribute(key, attrs[key]);
      });
    }
    (children || []).forEach(function (child) {
      if (child == null) return;
      node.appendChild(typeof child === "string" ? document.createTextNode(child) : child);
    });
    return node;
  }

  // Uses one of the <symbol> icons defined at the top of index.html.
  function icon(name) {
    var svg = document.createElementNS(SVG_NS, "svg");
    svg.setAttribute("aria-hidden", "true");
    svg.setAttribute("focusable", "false");
    var use = document.createElementNS(SVG_NS, "use");
    use.setAttribute("href", "#icon-" + name);
    svg.appendChild(use);
    return svg;
  }

  function clear(node) {
    while (node && node.firstChild) node.removeChild(node.firstChild);
  }

  function byId(id) { return document.getElementById(id); }

  // Opens a PDF in a new tab so the browser views it inline (no download).
  function openInNewTab(path) {
    var win = window.open(path, "_blank", "noopener");
    if (win) win.opener = null;
  }

  // Only keeps files that actually have a path, so a half-filled entry in
  // data.js degrades to a non-clickable card instead of a broken link.
  function usableFiles(item) {
    if (!item || !Array.isArray(item.files)) return [];
    return item.files.filter(function (file) {
      return file && typeof file.path === "string" && file.path.trim() !== "";
    });
  }

  /* ---------- card rendering ----------------------------------------- */

  /**
   * Builds one clickable card.
   * @param {Object} item     entry from SITE.projects or SITE.documents
   * @param {number} index    0-based, used for the 01 / 02 counter
   * @param {Object} options  { compact: true } hides the counter. Context and
   *                          tags show whenever the entry defines them.
   */
  function buildCard(item, index, options) {
    var opts = options || {};
    var files = usableFiles(item);
    var primary = files[0];
    var openable = Boolean(primary);

    var card = h("article", {
      class: "card" + (openable ? " is-openable" : " is-pending")
    });

    /* top row: counter + status chip (only when there is a file to open) */
    var status = openable ? h("span", { class: "card-status" }, [
      icon("arrow"),
      t(pick("ui.card.openHint"))
    ]) : null;

    card.appendChild(h("div", { class: "card-top" }, [
      opts.compact ? h("span", { class: "card-num" }) :
        h("span", { class: "card-num", text: String(index + 1).padStart(2, "0") }),
      status
    ]));

    /* title — a real link when a file exists, so it works with the keyboard */
    var title = h("h3", { class: "card-title" });
    if (openable) {
      title.appendChild(h("a", {
        href: primary.path,
        target: "_blank",
        rel: "noopener",
        text: t(item.title)
      }));
    } else {
      title.textContent = t(item.title);
    }
    card.appendChild(title);

    /* context line (projects, and documents that define one) */
    if (item.context) {
      card.appendChild(h("p", { class: "card-context", text: t(item.context) }));
    }

    /* one-line summary */
    if (item.summary) {
      card.appendChild(h("p", { class: "card-summary", text: t(item.summary) }));
    }

    /* tool tags */
    if (Array.isArray(item.tags) && item.tags.length) {
      card.appendChild(h("ul", { class: "tags" }, item.tags.map(function (tag) {
        return h("li", { class: "tag", text: tag });
      })));
    }

    /* file links — one small labeled link per file */
    if (openable) {
      var fileRow = h("div", { class: "card-files" });
      files.forEach(function (file) {
        fileRow.appendChild(h("a", {
          class: "file-link",
          href: file.path,
          target: "_blank",
          rel: "noopener"
        }, [icon("file"), t(file.label) || "PDF"]));
      });
      card.appendChild(fileRow);
    }

    /* clicking anywhere on the card opens the first file */
    if (openable) {
      card.addEventListener("click", function (event) {
        if (event.target.closest("a")) return;               // real links win
        var selection = window.getSelection();
        if (selection && String(selection).length > 0) return; // don't hijack text selection
        openInNewTab(primary.path);
      });
    }

    return card;
  }

  function renderCards(container, items, options) {
    clear(container);
    (items || []).forEach(function (item, index) {
      container.appendChild(buildCard(item, index, options));
    });
  }

  /* ---------- section rendering -------------------------------------- */

  function renderContacts() {
    var container = byId("contacts");
    clear(container);
    (SITE.profile.contacts || []).forEach(function (contact) {
      container.appendChild(h("a", {
        class: "contact",
        href: contact.href,
        rel: "noopener",
        target: contact.href.indexOf("mailto:") === 0 ? null : "_blank"
      }, [icon(contact.icon || "file"), contact.text]));
    });
  }

  function renderAbout() {
    var text = byId("about-text");
    clear(text);

    // Two accepted shapes per entry:
    //   { en: "...", fr: "..." }                          -> plain paragraph
    //   { heading: {en,fr}, text: {en,fr} }               -> headed section
    (SITE.about.paragraphs || []).forEach(function (paragraph) {
      var body = paragraph && paragraph.text ? paragraph.text : paragraph;
      if (paragraph && paragraph.heading) {
        text.appendChild(h("h3", { class: "about-heading", text: t(paragraph.heading) }));
      }
      text.appendChild(h("p", { text: t(body) }));
    });

    var list = byId("about-highlights");
    clear(list);
    (SITE.about.highlights || []).forEach(function (entry) {
      list.appendChild(h("dt", { text: t(entry.label) }));
      list.appendChild(h("dd", { text: t(entry.value) }));
    });
  }

  function renderCertifications() {
    var list = byId("cert-grid");
    if (!list) return;
    clear(list);

    (SITE.certifications || []).forEach(function (cert) {
      var item = h("li", { class: "cert" + (cert.inProgress ? " is-pending" : "") });

      /* name — becomes a link only when a credential URL is filled in */
      var name;
      if (cert.url) {
        name = h("a", {
          class: "cert-name",
          href: cert.url,
          target: "_blank",
          rel: "noopener",
          title: t(pick("ui.cert.credential"))
        }, [cert.name, icon("arrow")]);
      } else {
        name = h("span", { class: "cert-name", text: cert.name });
      }
      item.appendChild(name);

      item.appendChild(h("span", { class: "cert-meta" }, [
        h("span", { class: "cert-issuer", text: cert.issuer }),
        h("span", { class: "cert-date", text: t(cert.date) })
      ]));

      list.appendChild(item);
    });
  }

  function renderTryHackMe() {
    var host = byId("tryhackme");
    if (!host) return;
    clear(host);

    var data = SITE.tryhackme;
    if (!data || !Array.isArray(data.badges) || !data.badges.length) return;

    host.appendChild(h("h3", { class: "subsection-title", text: t(data.heading) }));
    if (data.note) {
      host.appendChild(h("p", { class: "section-note", text: t(data.note) }));
    }

    var row = h("ul", { class: "badge-row" });
    data.badges.forEach(function (badge) {
      var img = h("img", {
        class: "badge-img",
        src: badge.image,
        alt: t(badge.name),
        loading: "lazy",
        width: "56",
        height: "56"
      });
      var link = h("a", {
        class: "badge",
        href: badge.url,
        target: "_blank",
        rel: "noopener"
      }, [
        img,
        h("span", { class: "badge-name", text: t(badge.name) }),
        icon("arrow")
      ]);
      row.appendChild(h("li", {}, [link]));
    });
    host.appendChild(row);
  }

  /**
   * Builds schema.org Person structured data from the same content the page
   * renders, so it can never drift out of sync with data.js.
   * Note: the og: tags in index.html are static on purpose — social crawlers
   * do not run JavaScript, so those cannot be generated here.
   */
  function renderStructuredData() {
    var profile = SITE.profile;
    var siteUrl = (SITE.config && SITE.config.siteUrl) || "";

    var emailContact = (profile.contacts || []).filter(function (contact) {
      return typeof contact.href === "string" && contact.href.indexOf("mailto:") === 0;
    })[0];

    var sameAs = (profile.contacts || []).map(function (contact) {
      return contact.href;
    }).filter(function (href) {
      return /^https?:/.test(href);
    });

    var intro = (SITE.about.paragraphs || [])[0];
    if (intro && intro.text) intro = intro.text;

    var data = {
      "@context": "https://schema.org",
      "@type": "Person",
      name: profile.name,
      jobTitle: t(profile.tagline),
      description: t(intro),
      knowsLanguage: ["fr-CA", "en"],
      knowsAbout: (SITE.skills || []).reduce(function (all, group) {
        return all.concat((group.items || []).map(t));
      }, [])
    };
    if (siteUrl) data.url = siteUrl;
    if (emailContact) data.email = emailContact.href.replace("mailto:", "");
    if (sameAs.length) data.sameAs = sameAs;

    if (profile.address) {
      data.address = {
        "@type": "PostalAddress",
        addressLocality: profile.address.locality,
        addressRegion: profile.address.region,
        addressCountry: profile.address.country
      };
    }

    var credentials = (SITE.certifications || []).filter(function (cert) {
      return !cert.inProgress;
    }).map(function (cert) {
      return {
        "@type": "EducationalOccupationalCredential",
        name: cert.name,
        credentialCategory: "certificate",
        recognizedBy: { "@type": "Organization", name: cert.issuer }
      };
    });
    if (credentials.length) data.hasCredential = credentials;

    var tag = byId("structured-data");
    if (!tag) {
      tag = document.createElement("script");
      tag.type = "application/ld+json";
      tag.id = "structured-data";
      document.head.appendChild(tag);
    }
    tag.textContent = JSON.stringify(data, null, 2);
  }

  function renderSkills() {
    var grid = byId("skills-grid");
    clear(grid);
    (SITE.skills || []).forEach(function (group) {
      grid.appendChild(h("div", { class: "skill-group" }, [
        h("h3", { text: t(group.group) }),
        h("ul", { class: "skill-list" }, (group.items || []).map(function (item) {
          return h("li", { text: t(item) });
        }))
      ]));
    });
  }

  // Fills every element that carries data-i18n / data-bind.
  function renderStaticText() {
    document.querySelectorAll("[data-i18n]").forEach(function (node) {
      node.textContent = t(pick(node.getAttribute("data-i18n")));
    });
    document.querySelectorAll("[data-bind]").forEach(function (node) {
      var value = pick(node.getAttribute("data-bind"));
      node.textContent = typeof value === "string" ? value : t(value);
    });
  }

  function renderToggle() {
    var button = byId("lang-toggle");
    button.setAttribute("aria-label", t(pick("ui.langToggleLabel")));
    button.querySelectorAll("[data-lang-opt]").forEach(function (option) {
      option.setAttribute("data-active", String(option.getAttribute("data-lang-opt") === lang));
    });
  }

  /* ---------- main -------------------------------------------------- */

  function render() {
    document.documentElement.setAttribute("lang", lang);
    document.title = t(pick("ui.pageTitle")).replace("{name}", SITE.profile.name);

    renderStaticText();
    renderToggle();
    renderContacts();
    renderAbout();
    renderCards(byId("project-grid"), SITE.projects, { compact: false });
    renderCards(byId("document-grid"), SITE.documents, { compact: true });
    renderSkills();
    renderCertifications();
    renderTryHackMe();
    renderStructuredData();
  }

  function initialLang() {
    var configured = (SITE.config && SITE.config.defaultLang) === "fr" ? "fr" : "en";
    if (SITE.config && SITE.config.autoDetectBrowserLanguage) {
      var browser = (navigator.language || "").toLowerCase();
      if (browser.indexOf("fr") === 0) return "fr";
    }
    return configured;
  }

  // True when the visitor asked for less motion; the glitch is skipped then.
  function prefersReducedMotion() {
    return window.matchMedia &&
           window.matchMedia("(prefers-reduced-motion: reduce)").matches;
  }

  /**
   * Fires the language-switch glitch: a scanline veil plus a brief tear on
   * the headings. Purely a CSS class — see the .is-glitching rules. The class
   * is removed on animationend, with a timeout as a fallback in case the
   * event never lands (e.g. the element is off-screen).
   */
  var glitchTimer = null;
  function runGlitch() {
    if (prefersReducedMotion()) return;
    var body = document.body;
    body.classList.remove("is-glitching");
    void body.offsetWidth;                 // restart the animation
    body.classList.add("is-glitching");
    window.clearTimeout(glitchTimer);
    glitchTimer = window.setTimeout(function () {
      body.classList.remove("is-glitching");
    }, 400);
  }

  // Hairline progress bar across the top. Passive listener, one rAF per frame.
  function initScrollProgress() {
    var bar = byId("scroll-progress");
    if (!bar) return;
    var ticking = false;
    function update() {
      var doc = document.documentElement;
      var max = doc.scrollHeight - doc.clientHeight;
      var pct = max > 0 ? (doc.scrollTop / max) * 100 : 0;
      bar.style.width = pct.toFixed(2) + "%";
      ticking = false;
    }
    window.addEventListener("scroll", function () {
      if (!ticking) { ticking = true; window.requestAnimationFrame(update); }
    }, { passive: true });
    window.addEventListener("resize", update, { passive: true });
    update();
  }

  function init() {
    // Friendly message if data.js has a syntax error or was renamed.
    if (typeof SITE === "undefined") {
      document.body.insertAdjacentHTML("afterbegin",
        '<p style="padding:20px;font-family:monospace;color:#ff6b6b">' +
        "Could not load data.js — check the file for a missing comma or bracket." +
        "</p>");
      return;
    }

    lang = initialLang();
    render();

    byId("lang-toggle").addEventListener("click", function () {
      lang = lang === "en" ? "fr" : "en";
      render();
      runGlitch();
    });

    byId("footer-year").textContent = String(new Date().getFullYear());
    initScrollProgress();
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", init);
  } else {
    init();
  }
})();
